stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
    params:
    - data_ingestion.test_size
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - src/data/data_preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/processed/test.csv
    - data/processed/train.csv
    - src/features/feature_engineering.py
    outs:
    - data/interim/test_tfidf.csv
    - data/interim/train_tfidf.csv
    params:
    - feature_engineering.max_features
  model_training:
    cmd: python src/models/modelling.py
    deps:
    - src/models/modelling.py
    - data/interim/train_tfidf.csv
    outs:
    - models/random_forest_model.pkl
    params:
    - modelling.n_estimators
    - modelling.max_depth
  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - data/interim/test_tfidf.csv
    - src/models/model_evaluation.py
    - models/random_forest_model.pkl

    outs:
    - reports/metrics.json
