stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/data.csv
  data_preprocessing:
    cmd: python src\data_preprocessing.py
    deps:
    - .\src\data\data_preprocessing.py
    - data\raw\test.csv
    - data\raw\train.csv
    outs:
    - .\data\processed\train.csv
    - dta\processed\test.csv
